CREATE DATABASE OTHELLO

USE OTHELLO

CREATE TABLE JUGADOR 
(
	USERNAME VARCHAR(50) PRIMARY KEY NOT NULL,
	NOMBRES VARCHAR(75) NOT NULL,
	APELLIDOS VARCHAR(75) NOT NULL,
	PASSWRD VARCHAR(75) NOT NULL,
	FECHA_NAC DATE,
	CORREO_E VARCHAR(100),
	PAIS VARCHAR(100)
)

CREATE TABLE PARTIDA
(
	ID_PARTIDA INT PRIMARY KEY,
	ID_TIPO_PARTIDA INT,
	ID_TABLERO INT
)

CREATE TABLE PARTIDA_JUGADOR
(
	ID_PARTIDA_JUGADOR INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_PARTIDA INT,
	ID_JUGADOR VARCHAR(50),
)

CREATE TABLE TIPO_PARTIDA
(
	ID_TIPO_PARTIDA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	DESCRIPCION VARCHAR(200) NOT NULL,
)

CREATE TABLE TABLERO
(
	ID_TABLERO INT PRIMARY KEY NOT NULL,
)


CREATE TABLE FICHA
(
	ID_FICHA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COLOR VARCHAR(50),
)

CREATE TABLE TABLERO_FICHA
(
	ID_TABLERO INT,
	ID_FICHA INT,
	FILA INT,
	COLUMNA VARCHAR(2)
)


ALTER TABLE PARTIDA_JUGADOR 
    ADD CONSTRAINT FK_JUGADOR_PARTIDA FOREIGN KEY (ID_JUGADOR) REFERENCES JUGADOR (USERNAME)
ALTER TABLE PARTIDA_JUGADOR 
    ADD CONSTRAINT FK_PARTIDA FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDA (ID_PARTIDA)


ALTER TABLE PARTIDA
    ADD CONSTRAINT FK_TIPO_PARTIDA FOREIGN KEY (ID_TIPO_PARTIDA) REFERENCES TIPO_PARTIDA (ID_TIPO_PARTIDA)
ALTER TABLE PARTIDA
    ADD CONSTRAINT FK_TABLERO FOREIGN KEY (ID_TABLERO) REFERENCES TABLERO (ID_TABLERO)


ALTER TABLE TABLERO_FICHA
    ADD CONSTRAINT FK_TABLERO_FICHA FOREIGN KEY (ID_TABLERO) REFERENCES TABLERO (ID_TABLERO)
ALTER TABLE TABLERO_FICHA
    ADD CONSTRAINT FK_FICHA FOREIGN KEY (ID_FICHA) REFERENCES FICHA (ID_FICHA)


